version: 2
updates:
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to
    # specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: '/'
    schedule:
      interval: 'weekly'
    registries:
      - notifycal-github

  - package-ecosystem: 'terraform'
    directories:
      - '/'
      - '/modules/**'
      - '/tf'
      - '/tf/**'
    schedule:
      interval: 'weekly'
    registries:
      - notifycal-github

registries:
  notifycal-github:
    type: git
    url: 'https://github.com'
    username: x-access-token
    password: ${{secrets.DEPENDABOT_PAT}}
